name: ead_mobile_app
description: "EAD Demir & Çelik Resmi Mobil Yönetim Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.3+1
  intl: any
  pdf: ^3.10.8
  printing: ^5.13.1
  shared_preferences: ^2.2.3
  onesignal_flutter: ^5.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
